### ISSUE TITLE
Results printed from within (begin ...)

### ISSUE THREAD

**Issue by alexgian** [alexgian/rat#4]
Values returned inside of (begin ..) statement are being printed!
Why?  I thought that only the last value was actually returned.

It's making the initialisation routines look messy.  Actually, I don't want to see anything printed from them.

(I'll add the file details where this happens later)

**Comment by LiberalArtist** [comment]
A `begin` form at the module level or in an internal definition context is spliced into its surrounding context.

**Comment by alexgian** [comment]
OK, thanks.
Resolved by enclosing all offenders in (void ***).
